import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/videos">
          <div
            style={{
              backgroundColor: "gray",
              padding: "10px",
              borderRadius: "5px",
            }}
          >
            Click to Video Download Demo
          </div>
        </Link>
      </main>
    </div>
  );
}
